#!/bin/sh

alias mdh="Mandaya Hospital Group | xclip -sel c"
alias ebi="echo -n 'PT Etana Biotechnologies Indonesia' | xclip -sel c"
alias ctt="echo -n 'PT Citra Tubindo Tbk' | xclip -sel c"
alias ats="echo -n 'PT Atlas Petrochem Indo' | xclip -sel c"
alias bu="dconf dump /org/gnome/ > ~/marc/GitHub/ubuntu/gnome-backup"
alias wezterm='flatpak run org.wezfurlong.wezterm'

alias caly="cal -m $1"
alias gcal="gcal -H '\e[31;42m:\e[0m:\e[33;45m:\e[0m' -n -q ID $1"
alias chol="gcal -n long -q=ID $1"
alias c23="cat ~/Dropbox/cal2023.txt"
alias c24="cat ~/Dropbox/cal2024.txt"
# Creating calendar year file
# script filename.txt
# caly cal2024
# exit

# unsorted
alias x="xmodmap ~/.config/.Xmodmap"
#alias lf="~/marc/github/dotfiles/config/lf-ueberzug/lf-ueberzug"
alias lb="lsblk"
alias cps="rsync -aurviP --backup --suffix=.backup "
#alias lk="lf-kitty"
#alias lf="lf-ueberzug"
alias lo="libreoffice"
alias phone="ssh u0_a570@192.168.0.7 -p 8022"
alias cfont="fc-list | grep -i " #query for font installed
alias cfont="ffc-cache -vf"      #clear font cache
# Check xdg-mime
alias xf="xdg-mime query filetype "
#example: $ xdg-mime query filetype photo.jpeg
alias setwbg="swaybg -m fill -i "
# Need Root Privileges Files
alias esddm="sudo nvim /etc/sddm.conf.d/sddm.conf"
alias e0="et Dropbox/Cash\ Flow/Expense/2019-1.xlsx &"
#alias swaylock="swaylock \
#	--screenshots \
#	--clock \
#	--indicator \
#	--indicator-radius 100 \
#	--indicator-thickness 7 \
#	--effect-blur 7x5 \
#	--effect-vignette 0.5:0.5 \
#	--ring-color bb00cc \
#	--key-hl-color 880033 \
#	--line-color 00000000 \
#	--inside-color 00000088 \
#	--separator-color 00000000 \
#	--grace 2 \
#	--fade-in 0.2"

alias tsddm="sddm-greeter --test-mode --theme /usr/share/sddm/themes/maldives"
alias xd="xdg-mime default "
#example:
#$ xdg-mime default feh.desktop image/jpeg
#$ xdg-mime default wps-office-et.desktop text/html

# Configuration file
alias cfh="cd /etc;sudo nvim hosts"
alias cfhr="cd /etc;sudo nvim hosts && ranger /etc"
alias cfnr="cd ~/github/dotfile; nvim applysymlink.sh && ranger ~/github/dotfile"
alias cfn="cd ~/github/dotfile; nvim applysymlink.sh"
alias cfa="cd ~/github/dotfile; nvim .aliases"

alias cfw="cd ~/github/suckless/dwm && nvim config.def.h"
alias cfm="cd ~/github/suckless/dmenu && nvim config.def.h"
alias cft="cd ~/github/suckless/st && nvim config.def.h"
alias cfb="cd ~/github/suckless/blocks; nvim config.h"
alias cfx="cd ~/; nvim .xinitrc"
alias cfz="cd ~/; nvim .zshrc"
alias cfr="cd ~/.config/ranger/; nvim rc.conf"

# Git

alias gs="git status"
alias gb="git branch"
alias gbd="git branch -d" # delete branch
alias gc="git clone"
alias gcl="git clean -fdx"
alias gl="git log --oneoline"
alias gcom="git checkout master"
alias gr="git reset"
alias gco="git checkout"

alias cdd="cd ~/github/dotfile"
alias cdw="cd ~/github/suckless/dwm"
alias cdm="cd ~/github/suckless/dmenu-5.2"
alias cds="cd ~/github/suckless/st"

# Jump to folder
alias p="cd ~/Dropbox/Dataon/Project/"
alias d="cd ~/Dropbox"
alias o="cd ~/Downloads"
alias a="cd ~/Dropbox/Dataon/"
alias s="cd ~/github/suckless/st"
alias w="cd ~/github/suckless/dwm"
alias b="cd ~/.local/bin"
alias c="cd ~/.local/config"
alias m="cd ~/marc"
alias n="cd ~/Dropbox/notes/"
alias na="cd ~/Dropbox/notes/dataon"
alias np="cd ~/Dropbox/notes/personal"
alias nt="cd ~/Dropbox/notes/tech"
alias dot="cd ~/github/dotfile"
alias cdf="cd ~/files"
alias myp="cd ~/Dropbox/MyProject"
alias rea="cd ~/Dropbox/MyProject/react-app-src"
alias src="cd ~/Desktop/react-app/src"

alias dc="/home/mc/Dropbox/linux/dotfiles/.local/bin/custom"

alias gp="cd ~/Documents/ && yt-dlp -f '\''bestaudio'\'' "

alias tso="tmux source ~/.config/tmux/tmux.conf"
alias nw="tmux neww"
alias kw="tmux kill-window"
alias ks="tmux kill-server"
alias tr="tmux attach -t tr || tmux new -s tr"
alias tt="tmux attach -t ide || tmux new -s ide ws"
alias clf="tmux split -h lf; lf"

alias ya="yt-dlp -o '%(channel)s_%(title)s.%(ex wst)s'\'' -f '\''bestaudio'\'' '"
#alias ya="yt-dlp -o '~/secondary/youtube/audio/%(channel)s_%(title)s.%(ext)s' -f 'bestaudio' "
alias ys="yt-dlp -o '~/%(channel)s_%(title)s_%(height)s.%(ext)s' -f 18 "
alias yh="yt-dlp -o '~/%(channel)s_%(title)s_%(height)s.%(ext)s' -f 22 "
alias yf="yt-dlp -o '~/%(channel)s_%(title)s_%(height)s.%(ext)s' -f 'bestvideo[height<=1080][ext=mp4]+ba[ext=m4a]' "
alias yf="yt-dlp -o '~/%(channel)s-%(title)s.%(ext)s' -f 'bestvideo[height<=1080][ext=mp4]+ba[ext=m4a]' "

# Chris titus
# # ex - archive extractor
# # usage: ex <file>
# ls, the common ones I use a lot shortened for rapid fire usage
alias ls='lsd'
alias l='ls -lFh'   #size,show type,human readable
alias la='ls -lAFh' #long list,show almost all,show type,human readable
alias lr='ls -tRFh' #sorted by date,recursive,show type,human readable
alias lt='ls -ltFh' #long list,sorted by date,show type,human readable
alias ll='ls -l'    #long list
alias ldot='ls -ld .*'
alias lS='ls -1FSsh'
alias lart='ls -1Fcart'
alias lrt='ls -1Fcrt'

alias zshrc='${=EDITOR} ~/.zshrc' # Quick access to the ~/.zshrc file

alias grep='grep --color'
alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS} '

alias t='tail -f'

# Command line head / tail shortcuts
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"
alias -g M="| most"
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
#alias -g P="2>&1| pygmentize -l pytb"

alias dud='du -d 1 -h'
alias duf='du -sh *'
# alias fd='find . -type d -name'
alias ff='find . -type f -name'

alias h='history'
alias hgrep="fc -El 0 | grep"
alias help='man'
alias p='ps -f'
alias sortnr='sort -n -r'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'

# Battery
alias batstat='sudo tlp-stat -b'
alias batfull='sudo tlp fullcharge'
alias bat30='sudo tlp setcharge 25 30 BAT1'
alias bat90='sudo tlp setcharge 85 90 BAT1'
alias bat95='sudo tlp setcharge 90 95 BAT1'

alias blkid="sudo blkid"
alias dd='sudo dd if=~/Downloads/file.iso of=/dev/sdc bs=1M status=progress'
alias umt='sudo umount /dev/sdc1'
alias scan='clamscan --recursive --infected  --max-filesize=4000M -l ~/scanlog.txt --move=/home/mc/clamav/ /'
alias rnet='sudo systemctl restart NetworkManager'
alias syn='rsync -urvP '

# Operating system specific aliases
if [[ $OSTYPE == darwin* ]]; then
	alias flush='dscacheutil -flushcache'
	# Apps
	alias browse="open -a /Applications/Google\ Chrome.app"
	# * Browse Azure Portal
	alias azure="browse https://preview.portal.azure.com"
fi

alias -g own="sudo chown -R mc:mc *"
alias p1="ping www.gmail.com -s 1000"
alias p2="ping 192.168.0.1 -s 1000"

# init window name for project libre
alias wm="wmname LG3D"

alias hist='history | dmenu -i -l 20 -p "history" | xclip -sel c'
alias df="df -h -x squashfs -x tmpfs -x devtmpfs"
alias lsmount="mount | column -t"
alias extip="curl icanhazip.com"

alias jabra='bluetoothctl power on; bluetoothctl connect 50:C9:71:5A:23:90'
alias jbl='bluetoothctl power on; bluetoothctl connect F4:BC:DA:A4:37:A5'
# alias bi="sudo apt --fix-broken install"
alias di="sudo dpkg -i"
# alias i="sudo apt install"
alias up="sudo pacman -Syu --noconfirm"
alias qs="sudo pacman -Qs | grep"
#alias ui="sudo pacman -Rs"
alias ui="sudo apt remove --purge"
alias i="sudo apt install"
alias mki="makepkg -si"
alias mkw="cdw; rm config.h && sudo make clean install"
alias mks="cds;rm config.h && sudo make clean install"

# top 5 processes that using most memory
alias mem5="ps auxf | sort -nr -k 4 | head -5"
alias cpu10="ps auxf | sort -nr -k 3 | head -10"
alias speedtest="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -"

alias ls='lsd'
alias ll='ls -alF'
alias la='lsd -A'
alias l='ls -CF'

alias so="source ~/.zshrc"
alias sox="source ~/.xinitrc"
alias v='nvim'
alias vim='nvim'
#alias vimdiff='nvim -d'
alias r='ranger'
#alias h='history | dmenu -i -l 20 -p "history" | xclip -sel c'
alias h='history | dmenu -i -l 20 -p "history" | wl-copy'

# OS
alias pow='sudo poweroff'
alias reb='sudo reboot'
alias sus="sudo systemctl suspend;slock;"
alias full="sudo tlp fullcharge"
alias cam="ffplay /dev/video0"
alias rn="sudo systemctl restart NetworkManager"

# mouse
alias rtl='xmodmap -e "pointer = 1 2 3"'
alias ltr='xmodmap -e "pointer = 3 2 1"'

# Suffix - opening file with default apps in zsh
alias -s {txt}='nvim'
alias -s {pdf,PDF}='zathura'
alias -s {jpg,JPG,png,PNG}='feh'
alias -s {ods,ODS,odt,ODT,odp,ODP,doc,DOC,docx,DOCX}='wps'
alias -s {xls,XLS,xlsx,XLSX,xlsm,XLSM,csv,CSV}='et'
alias -s {ppt,PPT,pptx,PPTX}='wpp'
alias -s {html,HTML}='chromium'
alias -s {mp4,MP4,mov,MOV,mkv,MKV}='vlc'
alias -s {zip,ZIP,war,WAR}="unzip -l"
alias -s {jar,JAR}="java -jar"
alias -s gz="tar -tf"
alias -s {tgz,TGZ}="tar -tf"
alias -s {tar.gz}="tar -xvf"

# Function
# Git

gmm() {
	git add .
	git commit -m "$1"
}

gpush() {
	git add .
	git commit -m "$1"
	git push
}

aliasname() {
	command $firstParam $secondParam
}

rsq() {
	WINDOW_ID=$(xdotool search --onlyvisible --name qutebrowser)
	xdotool windowsize $WINDOW_ID 1500 1000
	xdotool windowmove $WINDOW_ID 10 10
}

ex() {
	if [ -f $1 ]; then
		case $1 in
		*.tar.bz2) tar xjf $1 ;;
		*.tar.gz) tar xzf $1 ;;
		*.tar.xz) tar xJf $1 ;;
		*.bz2) bunzip2 $1 ;;
		*.rar) unrar x $1 ;;
		*.gz) gunzip $1 ;;
		*.tar) tar xf $1 ;;
		*.tbz2) tar xjf $1 ;;
		*.tgz) tar xzf $1 ;;
		*.zip) unzip -d $1 ;;
		*.Z) uncompress $1 ;;
		*.7z) 7z x $1 ;;
		*) echo "'$1' cannot be extracted via ex()" ;;
		esac
	else
		echo "'$1' is not a valid file"
	fi
}

setbg() {
	fullpath="$(pwd)/$1"
	cp "$fullpath" ~/Desktop/wallpaper.jpg
	feh --bg-scale ~/Desktop/wallpaper.jpg &
	notify-send -i "~/Desktop/wallpaper.jpg" "Wallpaper Changed."
}

mou() {
	sudo mount /dev/sd$1 ~/$2
}

alias umo="sudo umount /dev/sd$1"
