vim.cmd([[ cabbrev cdu Neotree right dir=~/marc/GitHub/ubuntu/ ]])
vim.cmd([[ cabbrev cdc Neotree right dir=~/.config/ ]])
vim.cmd([[ cabbrev cdn Neotree right dir=~/Dropbox/notes/ ]])
vim.cmd([[ cabbrev cdd Neotree right dir=~/Dropbox/notes/dataon/ ]])
vim.cmd([[ cabbrev cdw Neotree right dir=~/Dropbox/notes/sfwp/ ]])
vim.cmd([[ cabbrev cdt Neotree right dir=~/Dropbox/notes/tech/ ]])
vim.cmd([[ cabbrev cdp Neotree right dir=~/Dropbox/notes/personal/ ]])
vim.cmd([[ cabbrev cdg Neotree right dir=/home/mc/Dropbox/MyProject/go_tutorial ]])

-- vim.cmd([[ cabbrev cdu cd ~/marc/GitHub/ubuntu/ ]])
-- vim.cmd([[ cabbrev cdc cd ~/.config/ ]])
-- vim.cmd([[ cabbrev cdn cd ~/Dropbox/notes/ ]])
-- vim.cmd([[ cabbrev cdd cd ~/Dropbox/notes/dataon/ ]])
-- vim.cmd([[ cabbrev cdw cd ~/Dropbox/notes/sfwp/ ]])
-- vim.cmd([[ cabbrev cdt cd ~/Dropbox/notes/tech/ ]])
-- vim.cmd([[ cabbrev cdp cd ~/Dropbox/notes/personal/ ]])
-- vim.cmd([[ cabbrev cdg cd /home/mc/Dropbox/MyProject/go_tutorial ]])

-- vim.cmd([[ cabbrev cbd confirm bd ]])
vim.cmd([[ cabbrev help tab help ]])
