vim.cmd([[ cabbrev cnu Neotree reveal dir=~/marc/GitHub/ubuntu/ ]])
vim.cmd([[ cabbrev cnc Neotree reveal dir=~/.config/ ]])
vim.cmd([[ cabbrev cnn Neotree reveal dir=~/Dropbox/notes/ ]])
vim.cmd([[ cabbrev cnd Neotree reveal dir=~/Dropbox/notes/dataon/ ]])
vim.cmd([[ cabbrev cnw Neotree reveal dir=~/Dropbox/notes/sfwp/ ]])
vim.cmd([[ cabbrev cnt Neotree reveal dir=~/Dropbox/notes/tech/ ]])
vim.cmd([[ cabbrev cnp Neotree reveal dir=~/Dropbox/notes/personal/ ]])

vim.cmd([[ cabbrev cdu cd ~/marc/GitHub/ubuntu/ ]])
vim.cmd([[ cabbrev cdc cd ~/.config/ ]])
vim.cmd([[ cabbrev cdn cd ~/Dropbox/notes/ ]])
vim.cmd([[ cabbrev cdd cd ~/Dropbox/notes/dataon/ ]])
vim.cmd([[ cabbrev cdd cw ~/Dropbox/notes/sfwp/ ]])
vim.cmd([[ cabbrev cdt cd ~/Dropbox/notes/tech/ ]])
vim.cmd([[ cabbrev cdp cd ~/Dropbox/notes/personal/ ]])

vim.cmd([[ cabbrev bd bd! ]])
