vim.cmd([[ cabbrev nu Neotree reveal dir=~/marc/GitHub/ubuntu/ ]])
vim.cmd([[ cabbrev nc Neotree reveal dir=~/.config/ ]])
vim.cmd([[ cabbrev nn Neotree reveal dir=~/Dropbox/notes/ ]])
vim.cmd([[ cabbrev nd Neotree reveal dir=~/Dropbox/notes/dataon/ ]])
vim.cmd([[ cabbrev nw Neotree reveal dir=~/Dropbox/notes/sfwp/ ]])
vim.cmd([[ cabbrev nt Neotree reveal dir=~/Dropbox/notes/tech/ ]])
vim.cmd([[ cabbrev np Neotree reveal dir=~/Dropbox/notes/personal/ ]])

vim.cmd([[ cabbrev cu cd ~/marc/GitHub/ubuntu/ ]])
vim.cmd([[ cabbrev cc cd ~/.config/ ]])
vim.cmd([[ cabbrev cn cd ~/Dropbox/notes/ ]])
vim.cmd([[ cabbrev cd cd ~/Dropbox/notes/dataon/ ]])
vim.cmd([[ cabbrev cd cw ~/Dropbox/notes/sfwp/ ]])
vim.cmd([[ cabbrev ct cd ~/Dropbox/notes/tech/ ]])
vim.cmd([[ cabbrev cp cd ~/Dropbox/notes/personal/ ]])

vim.cmd([[ cabbrev bd bd! ]])
